# Application Configuration for Sports Pulse Leagues Service
spring.application.name=sports-pulse-leagues
server.port=8082
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework=${SPORTS_PULSE_LEVEL_LOGIN:WARN}
logging.level.root=${SPORTS_PULSE_LEVEL_LOGIN:INFO}
management.endpoints.web.exposure.include=health

# Documentation Configuration (Swagger/OpenAPI)
springdoc.api-docs.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.api-docs.version=OPENAPI_3_1

# ApiFootball API Configuration
sportspulse.leagues.api.football.base-url=${SPORTS_PULSE_API_FOOTBALL_BASE_URL}
sportspulse.leagues.api.football.api-key=${SPORTS_PULSE_API_FOOTBALL_KEY}
