# Application Configuration for Sports Pulse Leagues Service
spring.application.name=sports-pulse-leagues
server.port=8082
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework=${SPORTS_PULSE_LEVEL_LOGIN:WARN}
logging.level.root=${SPORTS_PULSE_LEVEL_LOGIN:INFO}

# Documentation Configuration (Swagger/OpenAPI)
springdoc.api-docs.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.api-docs.version=OPENAPI_3_1

# Base URL for accessing football data (API-Football)
api.sports.url=https://v3.football.api-sports.io

# Authentication key. This is retrieved from the .env file.
api.sport.key=${RAPIDAPI_KEY}
