# Application Configuration for Sports Pulse Standings Service
spring.application.name=sports-pulse-standings
server.port=8086
spring.config.import=optional:file:../.env[.properties]
logging.level.org.springframework=${SPORTS_PULSE_LEVEL_LOGIN:WARN}
logging.level.root=${SPORTS_PULSE_LEVEL_LOGIN:INFO}

# Documentation Configuration (Swagger/OpenAPI)
springdoc.api-docs.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.api-docs.version=OPENAPI_3_1
