#!/bin/bash
set -e

echo "starting databases: $SPORTS_PULSE_DATASOURCE_DB_AUTH y $SPORTS_PULSE_DATASOURCE_DB_NOTIFICATIONS"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$SPORTS_PULSE_DATASOURCE_DB_AUTH";
  CREATE DATABASE "$SPORTS_PULSE_DATASOURCE_DB_NOTIFICATIONS";
EOSQL