# Application Configuration for Sports Pulse Authentication Service
spring.application.name=sports-pulse-auth
server.port=8081
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework=${SPORTS_PULSE_LEVEL_LOGIN:WARN}
logging.level.root=${SPORTS_PULSE_LEVEL_LOGIN:INFO}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Datasource Configuration
spring.datasource.url=${SPORTS_PULSE_DATASOURCE_URL_AUTH}
spring.datasource.username=${SPORTS_PULSE_DATASOURCE_USERNAME}
spring.datasource.password=${SPORTS_PULSE_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPORTS_PULSE_JPA_DDL:validate}
spring.jpa.show-sql=${SPORTS_PULSE_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Documentation Configuration (Swagger/OpenAPI)
springdoc.api-docs.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:false}
springdoc.api-docs.version=OPENAPI_3_1
